config/routes.rb
JqueryRails::Application.routes.draw do
  match 'comments' => 'comments#create', :via => [:put]
  match 'say' => 'comments#say', :via => [:get]
  resources :comments

  root :to => "comments#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_attached_file :attachment
  has_attached_file :other_attachment
  validates :subject, :body, :presence => true
  do_not_validate_attachment_file_type :attachment
  do_not_validate_attachment_file_type :other_attachment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def handle_unverified_request
    raise(ActionController::InvalidAuthenticityToken)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :xml, :json
  respond_to :js, :only => [:create, :update, :destroy]
  # GET /comments
  # GET /comments.xml
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new
    #respond_with(@comment, :layout => false)
    respond_with do |format|
      format.html { render :layout => ! request.xhr? }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @comment = Comment.create(comment_params)
    if request.xhr? || remotipart_submitted?
      sleep 1 if params[:pause]
      render :layout => false, :template => (params[:template] == 'escape' ? 'comments/escape_test' : 'comments/create'), :status => (@comment.errors.any? ? :unprocessable_entity : :ok)
    else
      redirect_to comments_path
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])
    respond_with do |format|
      format.html{ redirect_to @comment }
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.destroy(params[:id])
  end

  def say
    render plain: params[:message]
  end

  private

  def comment_params
    params.require(:comment).permit(:subject, :body, :attachment, :other_attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr class='comment' id='comment-<%= comment.id %>'>
  <td><%= comment.subject %></td>
  <td><%= comment.body %></td>
  <td><%= link_to comment.attachment_file_name, comment.attachment.url if comment.attachment? %></td>
  <td><%= link_to comment.other_attachment_file_name, comment.other_attachment.url if comment.other_attachment? %></td>
  <td><%= link_to 'Show', comment %></td>
  <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
  <td><%= link_to 'Destroy', comment, :data => {:confirm => 'Are you sure?'}, :method => :delete, :remote => true %></td>
</tr>

app/views/comments/_form.html.erb
<%= form_for(@comment, :remote => (params[:action] == 'new' ? true : false)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend class='required'>
      Required fields
    </legend>
    <div class="field">
      <%= f.label :subject, :class => 'required' %><br />
      <%= f.text_field :subject, :required => true %>
    </div>
    <div class="field">
      <%= f.label :body, :class => 'required' %><br />
      <%= f.text_area :body, :required => true %>
    </div>
    <% if params[:attachment] %>
      <div class="field">
        <%= f.label :attachment, :class => 'required' %><br />
        <%= f.file_field :attachment, :required => true %>
      </div>
    <% end %>
    </fieldset>
  <div class="actions">
    <%= f.submit data:{:disable_with => 'Submitting...'} %>
  </div>
<% end %>

app/views/comments/_new_comment_links.html.erb
<div id='new-comment-links'>
  <%= link_to 'New Comment', new_comment_path, :remote => true, :'data-type' => 'html', :id => 'new-comment-link' %>
  <br />
  <%= link_to 'New Comment with Attachment', new_comment_path(:attachment => true), :remote => true, :'data-type' => 'html', :id => 'new-comment-attachment-link' %>
</div>

app/views/comments/create.html.erb
<span>
HTML response:
</span>

<table>
<%= render @comment %>
</table>

app/views/comments/create.js.erb
<% unless @comment.errors.any? %>
  $('#comments').append( '<%= escape_javascript(
    render @comment
  ) %>' );
  $('#new-comment-form-container').find('input:not(:submit),select,textarea').val('');
<% else %>
  var $form = $('#new_comment'),
      $errorDiv = $('<div id="error_explanation">'),
      $errorList = $('<ul>');
  <% @comment.errors.full_messages.each do |msg| %>
    $errorList.append('<li><%= escape_javascript msg %></li>');
  <% end %>
  $form.find('#error_explanation').remove();
  $form.prepend($errorDiv.append($errorList));
<% end %>

app/views/comments/create.json.erb
<%= @comment.to_json.html_safe %>

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/escape_test.html.erb
<%= text_field_tag :quote, '"' %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table id='comments'>
  <tr>
    <th>Subject</th>
    <th>Body</th>
    <th>Attachment</td>
    <th>Other Attachment</td>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <%= render @comments %>
</table>

<br />

<%= render 'new_comment_links' %>

app/views/comments/new.html.erb
<div id='new-comment-form-container'>
  <h1>New comment</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Cancel', comments_path, :id => 'cancel-button' %>
</div>

app/views/comments/show.html.erb
<table>
  <tr>
    <th>Subject</th>
    <th>Body</th>
    <th>Attachment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <%= render @comment %>
</table>

<br />

<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JqueryRails</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>